// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"CrossRiver/6-degrees/models"
)

// GetDegreesOfSeparationOKCode is the HTTP code returned for type GetDegreesOfSeparationOK
const GetDegreesOfSeparationOKCode int = 200

/*GetDegreesOfSeparationOK OK

swagger:response getDegreesOfSeparationOK
*/
type GetDegreesOfSeparationOK struct {

	/*
	  In: Body
	*/
	Payload *models.ActorFound `json:"body,omitempty"`
}

// NewGetDegreesOfSeparationOK creates GetDegreesOfSeparationOK with default headers values
func NewGetDegreesOfSeparationOK() *GetDegreesOfSeparationOK {

	return &GetDegreesOfSeparationOK{}
}

// WithPayload adds the payload to the get degrees of separation o k response
func (o *GetDegreesOfSeparationOK) WithPayload(payload *models.ActorFound) *GetDegreesOfSeparationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get degrees of separation o k response
func (o *GetDegreesOfSeparationOK) SetPayload(payload *models.ActorFound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDegreesOfSeparationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDegreesOfSeparationNotFoundCode is the HTTP code returned for type GetDegreesOfSeparationNotFound
const GetDegreesOfSeparationNotFoundCode int = 404

/*GetDegreesOfSeparationNotFound Actor not found within 6 degrees of Kevin Bacon

swagger:response getDegreesOfSeparationNotFound
*/
type GetDegreesOfSeparationNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ActorNotFound `json:"body,omitempty"`
}

// NewGetDegreesOfSeparationNotFound creates GetDegreesOfSeparationNotFound with default headers values
func NewGetDegreesOfSeparationNotFound() *GetDegreesOfSeparationNotFound {

	return &GetDegreesOfSeparationNotFound{}
}

// WithPayload adds the payload to the get degrees of separation not found response
func (o *GetDegreesOfSeparationNotFound) WithPayload(payload *models.ActorNotFound) *GetDegreesOfSeparationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get degrees of separation not found response
func (o *GetDegreesOfSeparationNotFound) SetPayload(payload *models.ActorNotFound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDegreesOfSeparationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
