// Code generated by go-swagger; DO NOT EDIT.

// Package restapi 6degrees
//
//  6 degrees of Kevin Bacon microservice
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
