// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "6 degrees of Kevin Bacon microservice",
    "title": "6degrees",
    "version": "0.1.0"
  },
  "paths": {
    "/calculate_degrees/{actorName}": {
      "get": {
        "operationId": "GetDegreesOfSeparation",
        "parameters": [
          {
            "type": "string",
            "name": "actorName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ActorFound"
            }
          },
          "404": {
            "description": "Actor not found within 6 degrees of Kevin Bacon",
            "schema": {
              "$ref": "#/definitions/ActorNotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Actor": {
      "type": "object",
      "properties": {
        "movie": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "ActorFound": {
      "description": "Actor Found",
      "type": "object",
      "properties": {
        "degreesOfSeparation": {
          "type": "integer"
        },
        "movies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Actor"
          }
        }
      }
    },
    "ActorNotFound": {
      "description": "Actor Not Found",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "6 degrees of Kevin Bacon microservice",
    "title": "6degrees",
    "version": "0.1.0"
  },
  "paths": {
    "/calculate_degrees/{actorName}": {
      "get": {
        "operationId": "GetDegreesOfSeparation",
        "parameters": [
          {
            "type": "string",
            "name": "actorName",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ActorFound"
            }
          },
          "404": {
            "description": "Actor not found within 6 degrees of Kevin Bacon",
            "schema": {
              "$ref": "#/definitions/ActorNotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Actor": {
      "type": "object",
      "properties": {
        "movie": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "ActorFound": {
      "description": "Actor Found",
      "type": "object",
      "properties": {
        "degreesOfSeparation": {
          "type": "integer"
        },
        "movies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Actor"
          }
        }
      }
    },
    "ActorNotFound": {
      "description": "Actor Not Found",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
