// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActorNotFound Actor Not Found
//
// swagger:model ActorNotFound
type ActorNotFound struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this actor not found
func (m *ActorNotFound) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this actor not found based on context it is used
func (m *ActorNotFound) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActorNotFound) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActorNotFound) UnmarshalBinary(b []byte) error {
	var res ActorNotFound
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
