// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActorFound Actor Found
//
// swagger:model ActorFound
type ActorFound struct {

	// degrees of separation
	DegreesOfSeparation int64 `json:"degreesOfSeparation,omitempty"`

	// movies
	Movies []*Actor `json:"movies"`
}

// Validate validates this actor found
func (m *ActorFound) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMovies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActorFound) validateMovies(formats strfmt.Registry) error {
	if swag.IsZero(m.Movies) { // not required
		return nil
	}

	for i := 0; i < len(m.Movies); i++ {
		if swag.IsZero(m.Movies[i]) { // not required
			continue
		}

		if m.Movies[i] != nil {
			if err := m.Movies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("movies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this actor found based on the context it is used
func (m *ActorFound) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMovies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActorFound) contextValidateMovies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Movies); i++ {

		if m.Movies[i] != nil {
			if err := m.Movies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("movies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActorFound) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActorFound) UnmarshalBinary(b []byte) error {
	var res ActorFound
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
